grep '营业收入' *.txt
grep '营业成本' *.txt
grep '营业税金及附加' *.txt
grep '管理费用' *.txt
grep '销售费用' *.txt
grep '流动资产' *.txt
grep '流动负债' *.txt
grep '超额现金' *.txt
grep '短期借款' *.txt
grep '应付票据' *.txt
grep '一年内到期的非流动负债' *.txt
grep '应付短期债券' *.txt
grep '固定资产净值' *.txt
grep '投资性房地产' *.txt
grep '联营合营企业投资收益' *.txt
grep '短期借款' *.txt
grep '应付票据' *.txt
grep '长期借款' *.txt
grep '应付债券' *.txt
grep '少数股东权益' *.txt
grep '可供出售金融资产' *.txt
grep '持有至到期投资' *.txt
grep '递延所得税负债' *.txt
grep '货币资金' *.txt
grep '短期投资' *.txt
grep '联营合营企业投资收益' *.txt
